### ISSUE TITLE
Quarg Hydra Blender Model

### ISSUE THREAD

**Issue by OcelotWalrus** [Adde-Endless-Sky-Mods/Fluff#2]
Hey! This is just a request, could you send me the Quarg Hydra blender 3D model?

Thanks in advance.

**Comment by DarcyManoel** [comment]
I'm sorry, no. I lost the file for it a long time ago.

**Comment by OcelotWalrus** [comment]
Was it you who made the model or someone else?

**Comment by DarcyManoel** [comment]
It was my model, I lost the computer it was on. I had no back-up.

**Comment by OcelotWalrus** [comment]
Thank you anyway, I'll stop bothering you.
